NAME = phonebook

FLAGS = -Wall -Wextra -Werror -g -std=c++98

SRC = Contact.cpp PhoneBook.cpp

MAIN = main.cpp

HEADERS = Contact.hpp PhoneBook.hpp

all :
	c++ ${FLAGS} ${SRC} ${MAIN} -o ${NAME}

fclean :
	rm -rf ${NAME}
