NAME = Bank

FLAGS = -Wall -Wextra -Werror -g -std=c++98

SRC = Account.cpp

MAIN = tests.cpp

HEADERS = Contact.hpp PhoneBook.hpp

all :
	c++ ${FLAGS} ${SRC} ${MAIN} -o ${NAME}

fclean :
	rm -rf ${NAME}
